apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: system-backend-config
spec:
  # ヘルスチェック設定
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 8080
  # URL書き換え設定
  cdn:
    enabled: false
  # セッション親和性
  sessionAffinity:
    affinityType: "NONE"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: csp-backend-config
spec:
  # CSP用の設定（将来用）
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 8080
