apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microfrontend-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    # IPアドレス直接アクセス用（ホスト名指定なし）
    - http:
        paths:
          # systemはルートパス
          - path: /
            pathType: Prefix
            backend:
              service:
                name: system-service
                port:
                  number: 80
          # AWS アプリ
          - path: /aws
            pathType: Prefix
            backend:
              service:
                name: aws-service
                port:
                  number: 80
          # GCP アプリ
          - path: /gcp
            pathType: Prefix
            backend:
              service:
                name: gcp-service
                port:
                  number: 80
