apiVersion: v1
kind: Service
metadata:
  name: system-service
  labels:
    app: system
  annotations:
    cloud.google.com/backend-config: '{"default": "system-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: system
