apiVersion: v1
kind: Service
metadata:
  name: system-service
  labels:
    app: system
  annotations:
    cloud.google.com/backend-config: '{"default": "system-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: system
---
apiVersion: v1
kind: Service
metadata:
  name: aws-service
  labels:
    app: aws
spec:
  selector:
    app: aws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-service
  labels:
    app: gcp
spec:
  selector:
    app: gcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
